/**
 * Builds dist/styles.css: tokens, base, then every component's CSS, all in
 * `@layer metro` so the app's own CSS wins without `!important`.
 *
 * `--index` only regenerates src/styles/index.css (the playground and tests
 * import it directly); with no flag it also bundles and minifies.
 */
import { Glob } from 'bun'
import { bundle } from 'lightningcss'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'

const root = resolve(import.meta.dir, '..')
const stylesDir = resolve(root, 'src/styles')
const entry = resolve(stylesDir, 'index.css')

const components = [...new Glob('src/components/**/*.css').scanSync({ cwd: root })].sort()
const lines = [
  '/* Generated by scripts/build-css.ts: do not edit. Add a component by giving it a .css file. */',
  '@layer metro;',
  "@import './tokens.css' layer(metro);",
  "@import './base.css' layer(metro);",
  ...components.map((file) => `@import './${relative(stylesDir, resolve(root, file))}' layer(metro);`),
  '',
]
writeFileSync(entry, lines.join('\n'))

if (!process.argv.includes('--index')) {
  const { code, warnings } = bundle({
    filename: entry,
    minify: true,
    // color-mix() and :has() set the floor; nothing older is worth lowering for.
    targets: { chrome: 111 << 16, safari: (16 << 16) | (4 << 8), firefox: 113 << 16 },
  })
  for (const w of warnings) console.warn(`${w.loc.filename}:${w.loc.line} ${w.message}`)
  const out = resolve(root, 'dist/styles.css')
  mkdirSync(dirname(out), { recursive: true })
  writeFileSync(out, code)
  console.log(`dist/styles.css  ${(code.length / 1024).toFixed(1)} kB  (${components.length} component files)`)
}
